#A EMPRESA NEWTON LOC LOCAÇÃO DE VEICULOS TE CONTRATOU PARA SER
#O NOVO DBA DA EMPRESA. AO ANALISAR A PARTE DE GERENCIAMENTO DOS
#DADOS MUITAS ALTERAÇÕES E ATÉ MELHORIAS PRECISAM SER FEITAS.
#ABAIXO AS MELHORIAS SUGERIDAS:

#################################################################################

#1 - CRIAÇÃO DE NOVOS USUARIOS: MARIA(ADM),ROBERTO(COMUM),ANDERSON(COMUM) E PAULA(ANALISTA).(TODOS LOCAIS)
#TODOS DEVEM TER SENHA E AS MESMAS DEVEM OBDECER AS SEGUINTES REGRAS:
#TODAS DEVEM EXPIRAR EM 180 DIAS
#TODAS DEVEM TER O número Máximo de falhas de login = 5
#E O tempo de bloqueio em dias = 1

CREATE USER 'MARIA'@'LOCALHOST' IDENTIFIED BY '123' 
PASSWORD EXPIRE INTERVAL 180 DAY FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LOCK_TIME 1;

CREATE USER 'ROBERTO'@'LOCALHOST' IDENTIFIED BY '1234'
PASSWORD EXPIRE INTERVAL 180 DAY FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LOCK_TIME 1;

CREATE USER 'ANDERSON'@'LOCALHOST' IDENTIFIED BY '12345'
PASSWORD EXPIRE INTERVAL 180 DAY FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LOCK_TIME 1;

CREATE USER 'PAULA'@'LOCALHOST' IDENTIFIED BY '123456'
PASSWORD EXPIRE INTERVAL 180 DAY FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LOCK_TIME 1;

SELECT * FROM MYSQL.USER;



##################################################################################

#2 - CRIAÇÃO DE NOVOS ROLES
#3 ROLES: ADM, ANALISTA,COMUM.
#ADM : ACESSA TODO SCHEMA NEWTON LOC .
#ANALISTA : ACESSA NEWTON, LOC MAS PARA APENAS INSERT,UPDATE E DELETE
#COMUM : SOMENTE PESQUISA NAS TABELAS DO NEWTON LOC
#APLIQUE AS PERMISSÕES AOS USUARIOS

CREATE ROLE 'ADM'@'LOCALHOST';
CREATE ROLE 'ANALISTA'@'LOCALHOST';
CREATE ROLE 'COMUM'@'LOCALHOST';

GRANT ALL ON newtonloc.* TO 'ADM'@'LOCALHOST';
GRANT INSERT, UPDATE, DELETE ON newtonloc.* TO 'ANALISTA'@'LOCALHOST';
GRANT SELECT ON newtonloc.* TO 'COMUM'@'LOCALHOST';

GRANT 'ADM'@'LOCALHOST' TO 'MARIA'@'LOCALHOST';
GRANT 'COMUM'@'LOCALHOST' TO 'ROBERTO'@'LOCALHOST';
GRANT 'COMUM'@'LOCALHOST' TO 'ANDERSON'@'LOCALHOST';
GRANT 'ANALISTA'@'LOCALHOST' TO 'PAULA'@'LOCALHOST';

SET DEFAULT ROLE 'ADM'@'LOCALHOST' TO 'MARIA'@'LOCALHOST';
SET DEFAULT ROLE 'COMUM'@'LOCALHOST' TO 'ROBERTO'@'LOCALHOST';
SET DEFAULT ROLE 'COMUM'@'LOCALHOST' TO 'ANDERSON'@'LOCALHOST';
SET DEFAULT ROLE 'ANALISTA'@'LOCALHOST' TO 'PAULA'@'LOCALHOST';

SHOW GRANTS FOR 'MARIA'@'LOCALHOST';


##################################################################################

#3 - CRIAÇÃO DE STORED PROCEDURED
#CRIE UMA PROCEDURED CHAMADA SP1 PARA calcular a soma
#de pontos de um cliente.
#use o nome do cliente.

###################################################################################

#4 - CRIAÇÃO DE TRIGGER
#CRIE UMA TRIGGER PARA APLICAR A PONTUAÇÃO
#QUE O CLIENTE VAI GANHAR
#AO ALUGAR UM CARRO, FORMULA:
#CLIENTE BASICO = 500
#CLIENTE INTERMEDIARIO = 1500
#CLIENTE PREMIUM = 2500

DELIMITER $$
CREATE TRIGGER Pontuacao_
AFTER INSERT ON LOCACAO
FOR EACH ROW 
BEGIN

DECLARE ID INT;
DECLARE TIPO_ varchar(30);

SET ID = NEW.fk_idCliente;
SET TIPO_ = (Select tipo from clientes where idCliente = ID);

IF (TIPO_ = 'Basico') THEN 
UPDATE clientes 
SET pontuacao = pontuacao + 500 WHERE idCliente = ID;

ELSE IF (TIPO_ = 'Intermediario') THEN 
UPDATE clientes 
SET pontuacao = pontuacao + 1500 WHERE idCliente = ID;

ELSE   
UPDATE clientes 
SET pontuacao = pontuacao + 2500 WHERE idCliente = ID;


END IF;
END IF;
END$$
DELIMITER ;


###################################################################################

#5 - CRIAÇÃO DE INDICES
#OS INDICES QUE DEVEM SER CRIADOS:
#CLIENTES : NOME,EMAIL,PONTUACAO,TIPO
#CARROS : FABRICANTE,FABRICANTE,COR,ANOFABRICACAO,POTENCIAMOTOR,CATEGORIA,QUILOMETRAGEM
#LOCACAO : DATALOCACAO,VALORDIARIA
#DIMENSOES : ALTURA,LARGURA,COMPRIMENTO,PESO,TANQUE,PORTAMALAS

alter table CLIENTES add index (NOME);
alter table CLIENTES add index (EMAIL);
alter table CLIENTES add index (PONTUACAO);
alter table CLIENTES add index (TIPO);

alter table CARROS add index (FABRICANTE);
alter table CARROS add index (FABRICANTE);
alter table CARROS add index (COR);
alter table CARROS add index (ANOFABRICACAO);
alter table CARROS add index (POTENCIAMOTOR);
alter table CARROS add index (CATEGORIA);
alter table CARROS add index (QUILOMETRAGEM);

alter table LOCACAO add index (DATALOCACAO);
alter table LOCACAO add index (VALORDIARIA);

alter table DIMENSOES add index (ALTURA);
alter table DIMENSOES add index (LARGURA);
alter table DIMENSOES add index (COMPRIMENTO);
alter table DIMENSOES add index (PESO);
alter table DIMENSOES add index (TANQUE);
alter table DIMENSOES add index (PORTAMALAS);



